### PR TITLE
Closes #11 : vs_metabolic test data draft created

### LINKED ISSUE #11: Test data: `vs_metabolic`
### Background Information

We need to create an `{admiralmetabolic}` version of `pharmaversesdtm::vs` because the patients in the existing `vs` dataset are not obese.

This dataset will eventually be moved to `{pharmaversesdtm}`, but for the moment we will create it within `{admiralmetabolic}`.

### Definition of Done

- [ ] top-level `data_raw` folder created to house `vs_metabolic`, i.e. the script that generates our metabolic version of `vs`
- [ ] `vs_metabolic` program set up. program should read in `vs`, keep only a few patients and edit all relevant tests (weight, BMI, etc) to make them obese.
- [ ] New `vs.metabolic` dataset documented in `data.R`

### PR DESCRIPTION
**Pull request by Siddhesh2097**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral family codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral<ext> (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the Reference page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by manciniedoardo** [comment]
@Siddhesh2097 i guess we hold off on this until we have @AndersAskeland merge in something for #12 ? As after that you can then use `dm_metabolic` directly.

**Comment by Siddhesh2097** [comment]
> @Siddhesh2097 i guess we hold off on this until we have @AndersAskeland merge in something for #12 ? As after that you can then use `dm_metabolic` directly.

Yes @manciniedoardo , we'll merge once dm_metabolic is ready

**Comment by manciniedoardo** [comment]
@Siddhesh2097 - #12 is now closed and merged, so please:

1. merge `main` into your feature branch
2. resolve any conflicts
3. update your script to use `dm_metabolic` 
4. check the failing code style and lintr checks to see if you can fix them (happy to support if not)

Thanks!

**Comment by Siddhesh2097** [comment]
@manciniedoardo  
Can you help me in resolving the checks ? I tried but I'm missing something.

**Comment by manciniedoardo** [comment]
Hi @Siddhesh2097, something funny seems to be happening here as your feature branch is way behind with respect to what is in `main`. I can see this because your PR has a lot more changes than I would expect. Can you try running `git checkout 11_create_vs_metabolic && git rebase main` and then pushing to see what happens?

**Comment by Siddhesh2097** [comment]
@manciniedoardo , 

image

**Comment by manciniedoardo** [comment]
> @manciniedoardo ,
> 
> image

Ok, try remove them, no big deal if something goes wrong as we are working in a feature branch

**Comment by Siddhesh2097** [comment]
> > @manciniedoardo ,
> > image
> 
> Ok, try remove them, no big deal if something goes wrong as we are working in a feature branch

Okay, I deleted those two files and ran a git pull origin main . These are the files in my git currently after pulling. Earlier , I had restored the files that I didn't work on and didn't want to commit those. Doing that, I realized there were few updates from main that were required and I manually re-updated them. This is the reason, we are seeing that feature branch is way behind w.r.t main branch.

image

**Comment by manciniedoardo** [comment]
> > > @manciniedoardo ,
> > > image
> > 
> > 
> > Ok, try remove them, no big deal if something goes wrong as we are working in a feature branch
> 
> Okay, I deleted those two files and ran a git pull origin main . These are the files in my git currently after pulling. Earlier , I had restored the files that I didn't work on and didn't want to commit those. Doing that, I realized there were few updates from main that were required and I manually re-updated them. This is the reason, we are seeing that feature branch is way behind w.r.t main branch.
> 
> image

ok, looks good, could you try resolve the conflict in `data.R` appropriately by updating the file to what you think it should look like, and then push?

**Comment by Siddhesh2097** [comment]
I updated the data.R , had to pull and push again . But as we deleted dm_metabolic.R, devtools::document() throws an error as we don't have that file now. 
Should I just create a new branch and push that for request ?

**Comment by manciniedoardo** [comment]
Hmm. something is still wrong as the changes asre still present. Not sure what happened here. I think the easiest and fastest solution would be if you create a new branch off of `main` and paste your code in there, then make a PR for that branch and close this one.

**Pull request closed without merging**
